### PR TITLE
Enable/disable gravatar via config

### PR DESCRIPTION
**Pull request by rascalking**
Defines a new `GRAVATAR_ENABLED` config option, defaulting to `True`, and plumbs it through to the menu, only attempting to display a gravatar when enabled.

I didn't see any plumbing for changing config options and restarting the dev server as part of the test suite, so didn't add any e2e tests.

### CODE REVIEW

**Comment by abidibo** [comment]
@rascalking it seems that the build fails to run on travis, can you see what's happening? I'm quite busy at the moment.

**Comment by rascalking** [comment]
Yup, I'll take a look.

**Comment by rascalking** [comment]
I'm afraid I'm at "I have no idea how travis is currently succeeding" stage of this.  I can repro this locally using django 4, but it also happens locally on the current master, which I can see is passing on travis.

In an attempt to make extra sure there was no local state I had that was causing the failure, I cobbled together a minimalized test under docker.  This test will fail reliably for me.

`Dockerfile` (needed to get chromedriver on the python:3.10-bullseye image):
```Dockerfile
FROM python:3.10-bullseye
RUN apt update && apt install -y chromium-driver git
```

`travis-test.sh` (basically the install, before_script, and script parts of `.travis.yml` converted to bash, with a clone of the repo added in):
```bash
#!/bin/bash

set -e
set -x

#export DJANGO_VERSION='Django>=2.2,<3.0'
#export DJANGO_VERSION='Django>=3.0,<3.3'
export DJANGO_VERSION='Django>=4.0'

pip install --upgrade pip
pip install $DJANGO_VERSION --upgrade
pip install google-api-core==1.23.0
pip install google-api-python-client==1.12.4
pip install google-auth==1.22.1
pip install google-auth-httplib2==0.0.4
pip install webdriver-manager
pip install python-dotenv
pip install django-tinymce
pip install django-admin-rangefilter
pip install django-admin-autocomplete-filter==0.6.1
pip install django-import-export
pip install docutils
pip install easy_thumbnails
pip install django-mptt
pip install reportlab
pip install svglib
django-admin --version
pip install selenium==3.141.0

cd /tmp
git clone https://github.com/otto-torino/django-baton.git
cd django-baton/testapp/app
python manage.py migrate && python manage.py runserver &
sleep 3
python manage.py test
```

build and run the test:
```bash
$ docker build -t batontest .
$ docker run -v $(pwd)/travis-test.sh:/tmp/travis-test.sh --rm batontest /tmp/travis-test.sh
```

**Comment by rascalking** [comment]
Pickup merge of current master seems to have resolved the issue.  I think I regenerated `baton.min.js` correctly (ran `npm run compile` before committing the pickup merge, since it was one of the conflicts), but not 100% on that.

**Pull request merged**
